--abbonati che hanno visto almeno una serie della rete r3 e nessuna di r2
SELECT V.USERNAME
FROM VISIONE V
WHERE EXISTS(SELECT *
FROM RETE R,SERIE S
WHERE S.CODICE=V.CODICE AND S.ID_RETE=R.ID_RETE AND R.ID_RETE='R3' AND
NOT EXISTS (SELECT *
FROM RETE R1, SERIE S1
WHERE S1.CODICE=V.CODICE AND S1.ID_RETE=R1.ID_RETE AND R1.ID_RETE='R2'));


--abbonati almeno una serie rete r3 oppure almenp una rete r4
SELECT A.USERNAME
FROM ABBONATO A 
WHERE EXISTS (SELECT V.USERNAME
FROM VISIONE V, SERIE S
WHERE V.USERNAME=A.USERNAME AND S.CODICE=V.CODICE AND S.ID_RETE='R3'
UNION ALL
SELECT V1.USERNAME
FROM VISIONE V1, SERIE S1
WHERE V1.USERNAME=A.USERNAME AND S1.CODICE=V1.CODICE AND S1.ID_RETE='R4');


--ABBONATO CHE NON HANNO VISTO NESSUNA SERIE THRILLER

SELECT A.USERNAME
FROM ABBONATO A
WHERE NOT EXISTS(
SELECT *
FROM VISIONE V, SERIE S
WHERE V.USERNAME=A.USERNAME AND S.CODICE=V.CODICE AND S.GENERE = 'Thriller');


--coppie di serie dello stesso genere
SELECT DISTINCT A.CODICE, B.CODICE
FROM SERIE A, SERIE B
WHERE A.CODICE < B.CODICE AND A.GENERE = B.GENERE;

--abbonati che hanno visto tutte le serie della rete r1
SELECT A.USERNAME
FROM ABBONATO A
WHERE NOT EXISTS(SELECT *
FROM SERIE S, VISIONE V
WHERE S.CODICE=V.CODICE AND V.USERNAME=A.USERNAME AND S.ID_RETE='R1');

--RETI DI CUI ALMENO UNA SERIE VISTA DA ABBONATO DA TORINO
SELECT R.ID_RETE
FROM RETE R
WHERE EXISTS(SELECT *
FROM SERIE S, VISIONE V, ABBONATO A
WHERE S.ID_RETE=R.ID_RETE AND V.CODICE=S.CODICE AND A.USERNAME = V.USERNAME AND
A.CITTA='Torino');


--abbonati che non hanno visto nessuna seria che sia stata vista anche da u05
SELECT A.USERNAME
FROM ABBONATO A
WHERE NOT EXISTS(SELECT *
FROM VISIONE V, SERIE S
WHERE V.USERNAME=A.USERNAME AND S.CODICE=V.CODICE AND EXISTS(SELECT *
FROM VISIONE V1
WHERE V1.CODICE=S.CODICE AND V1.USERNAME ='U05'));

--COPPIE DISTENTE DELLA STESSA RETE
SELECT DISTINCT A.CODICE, B.CODICE
FROM SERIE A, SERIE B
WHERE A.CODICE<B.CODICE AND A.ID_RETE=B.ID_RETE;


--ABBONATI VISTO TUTTE LE SERIE DELLA RETE R2
SELECT A.USERNAME
FROM ABBONATO A
WHERE NOT EXISTS(SELECT*
FROM VISIONE V, SERIE S
WHERE V.USERNAME=A.USERNAME AND V.CODICE=S.CODICE AND
S.ID_RETE<>'R2');

--SERIE CHE HANNO ALMENO UNA VISIONE GIÀ TERMINATA
SELECT S.CODICE
FROM SERIE S
WHERE EXISTS(SELECT *
FROM VISIONE V
WHERE V.CODICE = S.CODICE AND V.DATA_FINE IS NOT NULL);


--abbonati che hanno visto almeno una serie che non è stata vista da nessun'altro
--abbonato

SELECT V.USERNAME
FROM VISIONE V, ABBONATO A
WHERE V.USERNAME=A.USERNAME AND EXISTS (SELECT *
FROM SERIE S
WHERE S.CODICE =V.CODICE AND NOT EXISTS(
SELECT * 
FROM VISIONE V1, ABBONATO A1
WHERE V1.CODICE = S.CODICE AND A1.USERNAME<>A.USERNAME AND V1.USERNAME=A1.USERNAME));

--SERIE VISTE DA ABBONATI DI MILANO CHE SONO STATE VISTE ANCHE DA ABBONATI DI ROMA

SELECT S.CODICE
FROM SERIE S
WHERE EXISTS(SELECT *
FROM VISIONE V, ABBONATO A
WHERE V.USERNAME=A.USERNAME AND V.CODICE=S.CODICE AND A.CITTA='Milano' AND 
 EXISTS(SELECT *
FROM VISIONE V1, ABBONATO A1
WHERE V1.CODICE=S.CODICE AND V1.USERNAME=A1.USERNAME AND A1.CITTA='Roma' AND
A1.USERNAME <> A.USERNAME));


--RETI DI CUI NESSUNA SERIE È STATA VISTA DA ABBONATI DI ROMA
SELECT R.ID_RETE
FROM RETE R
WHERE NOT EXISTS(SELECT *
FROM VISIONE V, SERIE S, ABBONATO A
WHERE V.USERNAME=A.USERNAME AND S.CODICE=V.CODICE AND S.ID_RETE=R.ID_RETE AND
A.CITTA='Roma');

--coppie abbonati con lo stesso piano che abitano nella stessa città
SELECT DISTINCT A.USERNAME, B.USERNAME
FROM ABBONATO A, ABBONATO B
WHERE A.USERNAME<B.USERNAME AND A.PIANO=B.PIANO AND A.CITTA=B.CITTA;


--RETI DI CUI TUTTE LE SERIE SONO STATE VISTE DA ALMENO UN ABBONATO
SELECT R.ID_RETE
FROM RETE R
WHERE NOT EXISTS(SELECT *
FROM SERIE S
WHERE S.ID_RETE=R.ID_RETE AND NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.CODICE=S.CODICE));

--SERIE VISTE DA ALMENO UN ABBONATO DI MILANO
SELECT S.CODICE
FROM SERIE S
WHERE EXISTS(SELECT *
FROM VISIONE V, ABBONATO A
WHERE V.CODICE=S.CODICE AND A.USERNAME = V.USERNAME AND A.CITTA='Milano');

--le reti di cui non esiste nessuna serie vista da un abbonato di torino
SELECT R.ID_RETE
FROM RETE R
WHERE NOT EXISTS(SELECT *
FROM SERIE S, VISIONE V, ABBONATO A
WHERE S.ID_RETE=R.ID_RETE AND V.CODICE=S.CODICE AND A.USERNAME=V.USERNAME AND
A.CITTA='Torino');

--ABBONATI NESSUNA VISIONE CON VOTO ASSEGNATO
SELECT A.USERNAME
FROM ABBONATO A
WHERE NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.USERNAME=A.USERNAME AND V.VOTO IS NOT NULL);


--SERIE VISTE SIA DA U01 CHE DA U04
SELECT S.CODICE
FROM SERIE S
WHERE EXISTS(SELECT V.CODICE
FROM VISIONE V
WHERE V.CODICE=S.CODICE AND V.USERNAME = 'U01'AND EXISTS(SELECT V1.CODICE
FROM VISIONE V1
WHERE V1.CODICE=S.CODICE AND V1.USERNAME ='U04'));
