Ù--FILIALE(ID_FILIALE, CITTA,INDIRIZZO,TELEFONO)
--AUTO(TARGA,MODELLO,CATEGORIA,ANNO_IMMATRICOLAZIONE,ID_FILIALE)
--CLIENTE(ID_CLIENTE, NOME, COGNOME, CODICE_FISCALE,NUM_PATENTE,EMAIL)
--NOLEGGIO(TARGA,ID_CLIENTE,DATA_RITIRO,DATA_RICONSEGNA,KM_PERCORSI,VALUTAZIONE)

--AUTO IMMATRICOLATE PRIMA DEL 2020
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE A.ANNO_IMMATRICOLAZIONE <2020;

--AUTO MAI NOLEGGIATE
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.TARGA=A.TARGA);

--CLIENTI CHE NON HANNO NOLEGGIATO
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE);

--CLIENTI CHE NON HANNO MAI NOLEGGIATO SUV
SELECT C.NOME FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N, AUTO A
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.CATEGORIA='SUV');

--FILIALI SENZA AUTO SPORTIVA
SELECT F.ID_FILIALE, F.CITTA
FROM FILIALE F
WHERE NOT EXISTS(SELECT * FROM AUTO A
WHERE A.ID_FILIALE=F.ID_FILIALE AND A.CATEGORIA='sportiva');

--auto mai noleggiate da mario rossi
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N, CLIENTE C
WHERE A.TARGA=N.TARGA AND C.ID_CLIENTE=N.ID_CLIENTE AND C.NOME='Mario' AND
C.COGNOME='Rossi');

--clienti che hanno noleggiato sia una berlina sia una utilitaria
SELECT C.NOME FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N,NOLEGGIO N1, AUTO A, AUTO A1
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND A.TARGA=N.TARGA AND
N1.ID_CLIENTE=C.ID_CLIENTE AND A1.TARGA=N1.TARGA AND
A.TARGA<>A1.TARGA AND A.CATEGORIA='berlina' AND 
A1.CATEGORIA='utilitaria');

--clienti che hanno noleggiato sia da filiale 1 sia da 2
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.ID_FILIALE=1
INTERSECT
SELECT C1.NOME
FROM CLIENTE C1, NOLEGGIO N1, AUTO A1
WHERE C1.ID_CLIENTE=N1.ID_CLIENTE AND A1.TARGA=N1.TARGA AND
A1.ID_FILIALE=2;

--CLIENTI CHE HANNO NOLEGGIATO SIA UN'AUTO DEL 2021 SIA DEL 2023
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND 
A.ANNO_IMMATRICOLAZIONE=2021
INTERSECT
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.ANNO_IMMATRICOLAZIONE=2023;

--CLIENTI CHE HANNO NOLEGGIATO ALMENO UNA BERLINA, UN SUV E UNA SPORTIVA
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND 
A.CATEGORIA='SUV'
INTERSECT
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.CATEGORIA = 'berlina'
INTERSECT
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.CATEGORIA='sportiva';

--clienti che hanno noleggiato auto di tutte le categorie esistenti
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM AUTO A
WHERE NOT EXISTS(SELECT *
FROM NOLEGGIO N1, AUTO A1
WHERE C.ID_CLIENTE=N1.ID_CLIENTE AND A1.TARGA=N1.TARGA AND
A.CATEGORIA=A1.CATEGORIA));

--clienti che hanno noleggiato tutte le auto della filiale 1
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM AUTO A
WHERE A.ID_FILIALE=1 AND NOT EXISTS(SELECT * FROM NOLEGGIO N1, AUTO A1
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND A1.TARGA=N1.TARGA AND 
A.TARGA=A1.TARGA));

--CLIENTI CHE HANNO NOLEGGIATO TUTTE LE AUTO SPORTIVE
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM AUTO A
WHERE A.CATEGORIA='sportiva' AND NOT EXISTS(SELECT * FROM NOLEGGIO N1, AUTO A1
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N1.TARGA=A1.TARGA AND A.TARGA=A1.TARGA));

--CLIENTI CHE HANNO NOLEGGIATO TUTTE LE AUTO SUV
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM AUTO A
WHERE A.CATEGORIA='SUV' AND NOT EXISTS(SELECT * FROM NOLEGGIO N1, AUTO A1
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N1.TARGA=A1.TARGA AND A.TARGA=A1.TARGA));

--CLIENTI CHE HANNO NOLEGGIATO IN TUTTE LE FILIALI DI MILANO
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM FILIALE F 
WHERE F.CITTA='Milano' AND NOT EXISTS(SELECT * FROM NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.ID_FILIALE=F.ID_FILIALE));

--CLIENTI CHE HANNO NOLEGGIATO AUTO IN TUTTE LE CITTA IN CUI ESISTE UNA FILIALE
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM FILIALE F
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N, AUTO A, FILIALE F1
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.ID_FILIALE=F1.ID_FILIALE AND F.CITTA=F1.CITTA));

--CLIENTI NOLEGGIATO TUTTE AUTO IMMATRICOLATE NEL 2022
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS (SELECT * FROM AUTO A
WHERE A.ANNO_IMMATRICOLAZIONE=2022 AND NOT EXISTS(SELECT * 
FROM NOLEGGIO N, AUTO A1
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND N.TARGA=A1.TARGA AND
A1.TARGA=A.TARGA));

--AUTO NOLEGGIATE DA TUTTI I CLIENTI CHE HANNO NOLEGGIAYO ALMENO UNA SPORTIVA
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE NOT EXISTS(SELECT * FROM CLIENTE C WHERE EXISTS(SELECT *
FROM NOLEGGIO N1, AUTO A1 WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND
N1.TARGA=A1.TARGA AND A1.CATEGORIA='sportiva') AND NOT EXISTS(SELECT *
FROM NOLEGGIO N2 WHERE N2.ID_CLIENTE=C.ID_CLIENTE AND N2.TARGA=A.TARGA));

--COPPIE DI FILIALI NELLA STESSA CITTA
SELECT A.ID_FILIALE, B.ID_FILIALE
FROM FILIALE A, FILIALE B
WHERE A.ID_FILIALE<B.ID_FILIALE AND NOT EXISTS(SELECT *
FROM FILIALE C
WHERE C.ID_FILIALE=A.ID_FILIALE AND NOT EXISTS(SELECT *
FROM FILIALE D
WHERE D.ID_FILIALE=B.ID_FILIALE AND C.CITTA=D.CITTA));

--COPPIE DI AUTO DELLA STESSA CATEGORIA APPARTENENTI A CITTA DIVERSE
SELECT A.TARGA, B.TARGA
FROM AUTO A, AUTO B
WHERE A.TARGA<B.TARGA AND NOT EXISTS(SELECT * FROM AUTO C, FILIALE F1
WHERE C.ID_FILIALE=F1.ID_FILIALE AND A.TARGA=C.TARGA AND NOT EXISTS(
SELECT * FROM AUTO D, FILIALE F2
WHERE D.TARGA=B.TARGA AND F2.ID_FILIALE=D.ID_FILIALE AND
D.CATEGORIA=C.CATEGORIA AND F1.CITTA<>F2.CITTA));

--COPPIE DI AUTO APPARTENENTI ALLA STESSA FILIALE
SELECT A.TARGA, B.TARGA
FROM AUTO A, AUTO B
WHERE A.TARGA<B.TARGA AND NOT EXISTS(SELECT * FROM AUTO C
WHERE A.TARGA=C.TARGA AND NOT EXISTS(SELECT * FROM AUTO D
WHERE D.TARGA=B.TARGA AND C.ID_FILIALE=D.ID_FILIALE));

--CLIENTI CHE HANNO NOLEGGIATO STESSA AUTO IN DATE DI RITIRO DIVERSE
SELECT C.NOME, A.TARGA
FROM CLIENTE C, AUTO A
WHERE EXISTS(SELECT * FROM NOLEGGIO N,NOLEGGIO N1, AUTO A1
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND N.TARGA=A.TARGA AND
N1.ID_CLIENTE=C.ID_CLIENTE AND N1.TARGA=A1.TARGA AND
A.TARGA=A1.TARGA AND N.DATA_RITIRO<>N1.DATA_RITIRO); 

--COPPIE DI CLIENTI CHE HANNO NOLEGGIATO LA STESSA AUTO
SELECT DISTINCT A.NOME, B.NOME
FROM CLIENTE A, CLIENTE B
WHERE A.NOME<B.NOME AND EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2
WHERE N1.ID_CLIENTE=A.ID_CLIENTE AND N2.ID_CLIENTE=B.ID_CLIENTE AND
N1.TARGA=N2.TARGA);

--COPPIE DI AUTO IMMATRICOLATE NELLO STESSO ANNP
SELECT A.TARGA, B.TARGA
FROM AUTO A, AUTO B
WHERE A.TARGA<B.TARGA AND A.ANNO_IMMATRICOLAZIONE=B.ANNO_IMMATRICOLAZIONE;

--CLIENTI CON ALMENO DUE NOLEGGI
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS (SELECT * FROM NOLEGGIO N1, NOLEGGIO N2
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND
(N1.TARGA<>N2.TARGA OR N1.DATA_RITIRO<>N2.DATA_RITIRO));

--CLIENTE CON ESATTAMENTE UN NOLEGGI
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2
WHERE C.ID_CLIENTE=N1.ID_CLIENTE AND C.ID_CLIENTE=N2.ID_CLIENTE AND
(N1.TARGA<>N2.TARGA OR N1.DATA_RITIRO<>N2.DATA_RITIRO))AND EXISTS
(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE);

--CLIENTE CON ESATTAMENTE DUE NOLEGGI
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND 
(N1.TARGA<>N2.TARGA OR N1.DATA_RITIRO<>N2.DATA_RITIRO)) AND 
NOT EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2, NOLEGGIO N3
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND
N3.ID_CLIENTE=C.ID_CLIENTE AND
(N1.TARGA<>N2.TARGA OR N1.DATA_RITIRO<>N2.DATA_RITIRO) AND
(N2.TARGA<>N3.TARGA OR N2.DATA_RITIRO<>N3.DATA_RITIRO) AND
(N3.TARGA<>N1.TARGA OR N3.DATA_RITIRO<>N1.DATA_RITIRO));

--CLIENTI CON ALMENO 3 NOLEGGI
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2, NOLEGGIO N3
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND
N3.ID_CLIENTE=C.ID_CLIENTE AND
(N1.TARGA<>N2.TARGA OR N1.DATA_RITIRO<>N2.DATA_RITIRO)AND
(N2.TARGA<>N3.TARGA OR N2.DATA_RITIRO<>N3.DATA_RITIRO)AND
(N3.TARGA<>N1.TARGA OR N3.DATA_RITIRO<>N1.DATA_RITIRO));

--CLIENTI CHE HANNO NOLEGGIATO ALMENO DUE AUTO DIVERSE
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT *
FROM NOLEGGIO N1, NOLEGGIO N2, AUTO A1, AUTO A2
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND
A1.TARGA=N1.TARGA AND N2.TARGA=A2.TARGA AND A1.TARGA<>A2.TARGA);

--AUTO NOLEGGIATE DA ALMENO DUE CLIENTI DIVERSI
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2, CLIENTE C1, CLIENTE C2
WHERE N1.TARGA=A.TARGA AND N2.TARGA=A.TARGA AND C1.ID_CLIENTE=N1.ID_CLIENTE AND
C2.ID_CLIENTE=N2.ID_CLIENTE AND C1.ID_CLIENTE<>C2.ID_CLIENTE);

--AUTO NOLEGGIATE ESATTAMENTE UNA VOLTA
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE EXISTS(SELECT * FROM NOLEGGIO N WHERE N.TARGA=A.TARGA)
AND NOT EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2
WHERE N1.TARGA=A.TARGA AND N2.TARGA=A.TARGA AND
(N1.TARGA<>N2.TARGA OR N1.DATA_RITIRO<>N2.DATA_RITIRO));

--CATEGORIE NOLEGGIATE DA ALMENO TRE CLIENTI DIVERSI
SELECT DISTINCT A.CATEGORIA
FROM AUTO A, AUTO A1, AUTO A2
WHERE EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2, NOLEGGIO N3
WHERE A.TARGA=N1.TARGA AND A1.TARGA=N2.TARGA AND A2.TARGA=N3.TARGA AND
N1.ID_CLIENTE<>N2.ID_CLIENTE AND A.CATEGORIA=A1.CATEGORIA AND
N2.ID_CLIENTE<>N3.ID_CLIENTE AND A1.CATEGORIA=A2.CATEGORIA AND
N3.ID_CLIENTE<>N1.ID_CLIENTE AND A.CATEGORIA=A2.CATEGORIA);

--CLIENTI CHE HANNO NOLEGGIATO AUTO DI ALMENO DUE CATEGORIE DIVERSE
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2, AUTO A1, AUTO A2
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND A1.TARGA=N1.TARGA AND
N2.ID_CLIENTE=C.ID_CLIENTE AND A2.TARGA=N2.TARGA AND
A1.CATEGORIA<>A2.CATEGORIA);

--CLIENTI CHE HANNO NOLEGGIATO ESCLUSIVAMENTE AUTO SPORTIVE(ALMENO UNA)
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM AUTO A WHERE A.CATEGORIA='sportiva' AND
NOT EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND A.TARGA=N.TARGA)) AND
EXISTS(SELECT * FROM AUTO A, NOLEGGIO N WHERE
A.TARGA=N.TARGA AND N.ID_CLIENTE=C.ID_CLIENTE AND A.CATEGORIA='sportiva');

--clienti che hanno noleggiato auto di una sola categoria
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT *
FROM AUTO A1, AUTO A2, NOLEGGIO N1, NOLEGGIO N2
WHERE A1.TARGA=N1.TARGA AND A2.TARGA=N2.TARGA AND
C.ID_CLIENTE=N1.ID_CLIENTE AND C.ID_CLIENTE=N2.ID_CLIENTE AND
A1.CATEGORIA<>A2.CATEGORIA) AND EXISTS(
SELECT * FROM NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE);

--CLIENTI SOLO AUTO DAL 2021 IN POI
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE) AND
NOT EXISTS (SELECT * FROM NOLEGGIO N1, AUTO A1
WHERE C.ID_CLIENTE=N1.ID_CLIENTE AND A1.TARGA=N1.TARGA AND
A1.ANNO_IMMATRICOLAZIONE <2021);

--CLIENTI SOLO DA FILIALI DI MILANO
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE) 
AND NOT EXISTS(SELECT * FROM NOLEGGIO N, AUTO A, FILIALE F
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND A.TARGA=N.TARGA AND A.ID_FILIALE=F.ID_FILIALE
AND F.CITTA<>'Milano');

--AUTO CHE HANNO RICEVUTO SOLO VALUTAZIONI PARI A 5(ALMENO UNA VALUTATA)
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE EXISTS(SELECT * FROM NOLEGGIO N WHERE
A.TARGA=N.TARGA AND N.VALUTAZIONE IS NOT NULL) 
AND NOT EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.TARGA=A.TARGA AND N.VALUTAZIONE<>5);

--CLIENTI HANNO SEMPRE DATO UNA VALUTAZIONE DI ALMENO 4
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
N.VALUTAZIONE IS NOT NULL) AND NOT EXISTS(SELECT *
FROM NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND N.VALUTAZIONE <4);

--NOLEGGI CON LA DURATA PIU LUNGA
SELECT N.TARGA, N.ID_CLIENTE
FROM NOLEGGIO N
WHERE N.DATA_RICONSEGNA IS NOT NULL AND NOT EXISTS(SELECT *
FROM NOLEGGIO N2
WHERE N2.DATA_RICONSEGNA IS NOT NULL AND
(N2.DATA_RICONSEGNA-N2.DATA_RITIRO)>
(N.DATA_RICONSEGNA-N.DATA_RITIRO));

--NOLEGGI CON DURATA PIU BREVE TRA QUELLI CONCLUSI
SELECT N.TARGA, N.ID_CLIENTE
FROM NOLEGGIO N
WHERE N.DATA_RICONSEGNA IS NOT NULL AND NOT EXISTS(SELECT *
FROM NOLEGGIO N2
WHERE N2.DATA_RICONSEGNA IS NOT NULL AND
(N2.DATA_RICONSEGNA-N2.DATA_RITIRO)<(N.DATA_RICONSEGNA-N.DATA_RITIRO));

--CLIENTI CHE HANNO ALMENO UN NOLEGGIO IN CORSO E ALMENO UNO CONCLUSO
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND N.DATA_RICONSEGNA IS NOT NULL
INTERSECT
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND N.DATA_RICONSEGNA IS NULL;

--79-NOLEGGI CONCLUSI MA NON VALUTATI
SELECT N.ID_CLIENTE, N.TARGA
FROM NOLEGGIO N
WHERE N.DATA_RICONSEGNA IS NOT NULL AND N.VALUTAZIONE IS NULL;

--CLIENTI CHE HANNO VALUTATO TUTTI I PROPRI NOLEGGI
SELECT C.NOME
FROM CLIENTE C WHERE EXISTS (SELECT * FROM NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE) AND NOT EXISTS(SELECT *
FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
N.VALUTAZIONE IS NULL);

--CLIENTI CON ALMENO UN NOLEGGIO MAI VALUTAZIONE >5
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE) AND
NOT EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
N.VALUTAZIONE =5);

--AUTO MAI VALUTATE
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.TARGA=A.TARGA AND N.VALUTAZIONE IS NOT NULL);

--IL NOLEGGIO CON PIU KM
SELECT N.ID_CLIENTE, N.TARGA
FROM NOLEGGIO N
WHERE KM_PERCORSI IS NOT NULL AND NOT EXISTS(SELECT *
FROM NOLEGGIO N2
WHERE N2.KM_PERCORSI>N.KM_PERCORSI);

--IL NOLEGGIO CON MENO KM
SELECT N.ID_CLIENTE, N.TARGA
FROM NOLEGGIO N
WHERE KM_PERCORSI IS NOT NULL AND NOT EXISTS(SELECT *
FROM NOLEGGIO N2
WHERE N2.KM_PERCORSI<N.KM_PERCORSI);

--L'AUTO PIU VECCHIA IN ASSOLUTO
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE A.ANNO_IMMATRICOLAZIONE IS NOT NULL AND NOT EXISTS(SELECT *
FROM AUTO A2
WHERE A2.ANNO_IMMATRICOLAZIONE<A.ANNO_IMMATRICOLAZIONE);

--LAUTO PIÙ RECENTE
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE A.ANNO_IMMATRICOLAZIONE IS NOT NULL AND NOT EXISTS(SELECT*
FROM AUTO A2
WHERE A2.ANNO_IMMATRICOLAZIONE>A.ANNO_IMMATRICOLAZIONE);

--CLIENTI CHE HANNO ALMENO UN NOLEGGIO PIÙ LUNGO DI TUTTI I NOLEGGI DI PAOLO 
SELECT C.NOME
FROM CLIENTE C
WHERE C.NOME<>'Paolo' AND EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
NOT EXISTS(SELECT * FROM NOLEGGIO N2, CLIENTE C2
WHERE C2.ID_CLIENTE=N2.ID_CLIENTE AND (N2.DATA_RICONSEGNA-N2.DATA_RITIRO)>
(N.DATA_RICONSEGNA-N.DATA_RITIRO)AND C2.NOME='Paolo'));

--CLIENTI ALMENO UN NOLEGGIO CON PIU KM DI ANNA

SELECT C.NOME
FROM CLIENTE C
WHERE C.NOME<>'Anna' AND EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE
AND NOT EXISTS(SELECT * FROM NOLEGGIO N2, CLIENTE C2
WHERE C2.ID_CLIENTE=N2.ID_CLIENTE AND (N2.DATA_RICONSEGNA-N2.DATA_RITIRO)>
(N.DATA_RICONSEGNA-N.DATA_RITIRO)AND C2.NOME='Anna'));

--PER OGNI CLIENTE, IL SUO NOLEGGIO CON PIU KM
SELECT N.TARGA, C.NOME, N.KM_PERCORSI
FROM CLIENTE C, NOLEGGIO N
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND
N.KM_PERCORSI IS NOT NULL AND NOT EXISTS(SELECT * FROM NOLEGGI N2
WHERE N2.ID_CLIENTE=C.ID_CLIENTE AND N2.KM_PERCORSI>N.KM_PERCORSI);

--CLIENTI CHE HANNO NOLEGGIATO ESATTAMENTE LE STESSE CATEGORIE DI ELENA NERI
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM AUTO A1, NOLEGGIO N1,CLIENTE C1
WHERE C1.ID_CLIENTE=N1.ID_CLIENTE AND N1.TARGA=A1.TARGA AND C1.NOME = 'Elena' AND 
NOT EXISTS(SELECT * FROM NOLEGGIO N2, AUTO A2
WHERE N2.ID_CLIENTE=C.ID_CLIENTE AND N2.TARGA=A2.TARGA AND 
A2.CATEGORIA=A1.CATEGORIA)) AND NOT EXISTS(SELECT * FROM NOLEGGIO N1, AUTO A1
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND A1.TARGA=N1.TARGA AND NOT EXISTS(
SELECT * FROM CLIENTE C1,NOLEGGIO N2, AUTO A2 WHERE A2.TARGA=N2.TARGA AND 
N2.ID_CLIENTE=C1.ID_CLIENTE AND C1.NOME='Elena' AND A2.CATEGORIA=A1.CATEGORIA));

--CLIENTI HANNO NOLEGGIATO ALMENO TUTTE LE CATEGORIE DI LUIGI
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS (SELECT * FROM NOLEGGIO N1, AUTO A1, CLIENTE C2
WHERE N1.ID_CLIENTE = C2.ID_CLIENTE AND A1.TARGA=N1.TARGA AND
C2.NOME='Luigi' AND NOT EXISTS(SELECT *
FROM NOLEGGIO N2, AUTO A2
WHERE N2.ID_CLIENTE=C.ID_CLIENTE AND A2.TARGA=N2.TARGA
AND A2.CATEGORIA=A1.CATEGORIA));

--AUTO NOLEGGIATE DA ALMENO UN CLIENTE CHE HA NOLEGGIATO UNA SPORTIVA
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE EXISTS (SELECT * FROM CLIENTE C1, NOLEGGIO N1
WHERE C1.ID_CLIENTE = N1.ID_CLIENTE AND N1.TARGA=A.TARGA AND EXISTS(SELECT*
FROM AUTO A2, NOLEGGIO N2
WHERE N2.ID_CLIENTE = C1.ID_CLIENTE AND A2.TARGA=N2.TARGA AND A2.CATEGORIA='sportiva'));

--CLIENTI CHE HANNO NOLEGGIATO ALMENO UN'AUTO DELLA STESSA CATEGORIA DI UN'AUTO
--NOLEGGIATA DA ANNA
SELECT C.NOME
FROM CLIENTE C
WHERE C.NOME <>'Anna' AND EXISTS (SELECT * FROM NOLEGGIO N1, AUTO A1
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND A1.TARGA=N1.TARGA AND EXISTS(
SELECT * FROM NOLEGGIO N2, AUTO A2, CLIENTE C2
WHERE N2.ID_CLIENTE=C2.ID_CLIENTE AND A2.TARGA=N2.TARGA AND
C2.NOME='Anna' AND A2.CATEGORIA=A1.CATEGORIA));

--CLIENTI CHE HANNO ALMENO UNA IMMATRICOLATA PRIMA DEL 2020
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N, AUTO A
WHERE A.TARGA=N.TARGA AND N.ID_CLIENTE=C.ID_CLIENTE AND
A.ANNO_IMMATRICOLAZIONE < 2020);

--CLIENTI CHE HANNO NOLEGGIATO UN'AUTO DI CATEGORIA SUV MA NESSUNA BERLINA
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS (SELECT * FROM AUTO A1, NOLEGGIO N1
WHERE A1.TARGA=N1.TARGA AND C.ID_CLIENTE=N1.ID_CLIENTE AND
A1.CATEGORIA='SUV' AND NOT EXISTS(SELECT * FROM NOLEGGIO N2, AUTO A2
WHERE C.ID_CLIENTE = N2.ID_CLIENTE AND A2.TARGA=N2.TARGA AND
A2.CATEGORIA = 'berlina'));

--clienti mai noleggiato due volte la stessa auto
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N1, AUTO A1, NOLEGGIO N2, AUTO A2
WHERE C.ID_CLIENTE=N1.ID_CLIENTE AND C.ID_CLIENTE=N2.ID_CLIENTE AND
N1.TARGA=A1.TARGA AND N2.TARGA=A2.TARGA AND A1.TARGA=A2.TARGA
AND N1.DATA_RITIRO<>N2.DATA_RITIRO) AND EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.ID_CLIENTE= C.ID_CLIENTE);

--CLIENTI CHE HANNO NOLEGGIATO ALMENO UN'AUTO NOLEGGIATA ANCHE DA MARIO
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N, AUTO A
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND A.TARGA=N.TARGA AND EXISTS(SELECT *
FROM NOLEGGIO N2, CLIENTE C2
WHERE N2.ID_CLIENTE=C2.ID_CLIENTE AND N2.TARGA = A.TARGA AND
C2.NOME ='Mario')); 

--CLIENTI MAI NOLEGGIATO DA FILIALE DI ROMA
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE) AND NOT EXISTS(SELECT * 
FROM NOLEGGIO N, AUTO A, FILIALE F
WHERE N.ID_CLIENTE= C.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.ID_FILIALE=F.ID_FILIALE AND F.CITTA='Roma');

--filiali che possiedono almeno un'auto mai noleggiata
SELECT F.ID_FILIALE
FROM FILIALE F
WHERE EXISTS(SELECT * FROM AUTO A WHERE 
A.ID_FILIALE=F.ID_FILIALE AND NOT EXISTS(SELECT *
FROM NOLEGGIO N WHERE N.TARGA=A.TARGA));

--NOLEGGI SU AUTO SUV CON VALUTAZIONE PARI A 5
SELECT N.ID_CLIENTE, N.TARGA
FROM NOLEGGIO N, AUTO A
WHERE A.TARGA=N.TARGA AND A.CATEGORIA='SUV' AND N.VALUTAZIONE=5;

--CLIENTI NOLEGGIATO ALMENO UN'AUTO IMMATRICOLATA NEL MEDESIMO ANNO DI PAOLO
SELECT C.NOME
FROM CLIENTE C
WHERE C.NOME<>'Paolo' AND EXISTS(SELECT * FROM NOLEGGIO N1, AUTO A1
WHERE A1.TARGA=N1.TARGA AND N1.ID_CLIENTE=C.ID_CLIENTE AND EXISTS(SELECT*
FROM NOLEGGIO N2, AUTO A2, CLIENTE C2
WHERE N2.ID_CLIENTE=C2.ID_CLIENTE AND C2.NOME='Paolo' AND A2.TARGA=N2.TARGA AND
A2.ANNO_IMMATRICOLAZIONE=A1.ANNO_IMMATRICOLAZIONE));

