--FILIALE(ID_FILIALE,CITTA,INDIRIZZO,TELEFONO)
--AUTO(TARGA,MODELLO,CATEGORIA,ANNO_IMMATRICOLAZIONE,ID_FILIALE)
--CLIENTE(ID_CLIENTE,NOME,COGNOME,CODICE_FISCALE,NUM_PATENTE,EMAIL)
--NOLEGGIO(TARGA,ID_CLIENTE,DATA_RITIRO,DATA_RICONSEGNA,KM_PERCORSI,VALUTAZIONE)

--CLIENTI ALMENO UN NOLEGGIO VALUTATO 5
SELECT C.ID_CLIENTE
FROM CLIENTE C
WHERE EXISTS (SELECT* FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
N.VALUTAZIONE=5);

--AUTO MAI NOLEGGIATE
SELECT A.TARGA
FROM AUTO A
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N WHERE N.TARGA=A.TARGA);

--CLIENTI CHE HANNO  NOLEGGIATO SIA UNA BERLINA SIA UN SUV
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS( SELECT * FROM NOLEGGIO N, AUTO A
WHERE N.ID_CLIENTE = C.ID_CLIENTE AND A.TARGA=N.TARGA AND A.CATEGORIA='SUV')
AND EXISTS (SELECT * FROM NOLEGGIO N1, AUTO A1 WHERE A1.CATEGORIA='berlina' AND
A1.TARGA=N1.TARGA AND N1.ID_CLIENTE=C.ID_CLIENTE);

--auto noleggiate sia da mario rossi sia da luigi verdi
SELECT A.TARGA
FROM AUTO A
WHERE EXISTS (SELECT * FROM NOLEGGIO N, CLIENTE C WHERE A.TARGA=N.TARGA AND
C.ID_CLIENTE=N.ID_CLIENTE AND C.NOME='Mario') AND EXISTS (SELECT *
FROM NOLEGGIO N1, CLIENTE C1 WHERE N1.TARGA=A.TARGA AND C1.NOME='Luigi' AND
C1.ID_CLIENTE=N1.ID_CLIENTE);

--CLIENTI CHE NON HANNO MAI EFFETTUATO UN NOLEGGIO
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE);

--CLIENTI CHE HANNO NOLEGGIATO SUV MA MAI UNA BERLINA
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS ( SELECT * FROM NOLEGGIO N, AUTO A WHERE A.CATEGORIA='SUV' AND
N.TARGA=A.TARGA AND N.ID_CLIENTE=C.ID_CLIENTE AND NOT EXISTS(SELECT*
FROM NOLEGGIO N1, AUTO A1 WHERE A1.CATEGORIA='berlina' AND A1.TARGA=N1.TARGA AND
C.ID_CLIENTE = N1.ID_CLIENTE));

--CLIENTI CHE HANNO NOLEGGIATO AUTO DI TUTTE LE CATEGORIE ESISTENTI
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT DISTINCT A.CATEGORIA
FROM AUTO A
WHERE  NOT EXISTS (SELECT* FROM NOLEGGIO N, AUTO A1
WHERE A1.TARGA=N.TARGA AND
N.ID_CLIENTE = C.ID_CLIENTE AND A1.CATEGORIA=A.CATEGORIA));

--CLIENTI CHE HANNO NOLEGGIATO TUTTE LE AUTO DELLA FILIALE 1
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS (SELECT * FROM AUTO A WHERE A.ID_FILIALE = 1 AND
NOT EXISTS(SELECT * FROM NOLEGGIO N WHERE N.TARGA=A.TARGA AND
C.ID_CLIENTE=N.ID_CLIENTE));

--FILIALI NELLA STESSA CITTÀ
SELECT A.ID_FILIALE, B.ID_FILIALE
FROM FILIALE A, FILIALE B
WHERE A.ID_FILIALE < B.ID_FILIALE AND NOT EXISTS(
SELECT * FROM FILIALE C WHERE C.ID_FILIALE = A.ID_FILIALE AND NOT EXISTS(SELECT*
FROM FILIALE D WHERE D.ID_FILIALE=B.ID_FILIALE AND D.CITTA=C.CITTA));

--CLIENTI CHE HANNO NOLEGGIATO LA STESSA AUTO IN DATE DI RITIRO DIVERSE
SELECT DISTINCT N.TARGA, C.NOME
FROM CLIENTE C, NOLEGGIO N, NOLEGGIO N1
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND N1.ID_CLIENTE=N.ID_CLIENTE AND
N1.TARGA=N.TARGA AND N.DATA_RITIRO< N1.DATA_RITIRO;

--NOLEGGI ANCORA IN CORSO
SELECT N.TARGA, N.ID_CLIENTE
FROM NOLEGGIO N
WHERE N.DATA_RICONSEGNA IS NULL;

--NOLEGGI CONCLUSI MA NON VALUTATI
SELECT N.TARGA, N.ID_CLIENTE
FROM NOLEGGIO N
WHERE N.DATA_RICONSEGNA IS NOT NULL AND N.VALUTAZIONE IS NULL;

--CLIENTI CHE HANNO  NOLEGGIATO UN AUTO SPORTIVA UNITI A QUELLI CON UN NOLEGGIO IN 
--CORSO
SELECT C.ID_CLIENTE, C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND A.CATEGORIA='sportiva'
UNION 
SELECT C1.ID_CLIENTE, C1.NOME
FROM CLIENTE C1, NOLEGGIO N1
WHERE C1.ID_CLIENTE=N1.ID_CLIENTE AND N1.DATA_RICONSEGNA IS NULL;

--CLIENTI CHE HANNO EFFETTUATO UN SOLO NOLEGGIO
SELECT C.ID_CLIENTE
FROM CLIENTE C
WHERE EXISTS(SELECT *
FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE AND NOT EXISTS(SELECT *
FROM NOLEGGIO N1 WHERE C.ID_CLIENTE = N1.ID_CLIENTE AND
(N1.TARGA<>N.TARGA OR N1.DATA_RITIRO<>N.DATA_RITIRO )));

--clienti che hanno noleggiato solo auto sportive
SELECT C.ID_CLIENTE, C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT *
FROM AUTO A, NOLEGGIO N
WHERE A.CATEGORIA='sportiva' AND N.ID_CLIENTE=C.ID_CLIENTE AND NOT EXISTS(SELECT *
FROM NOLEGGIO N, AUTO A1
WHERE A1.TARGA=N.TARGA AND C.ID_CLIENTE=N.ID_CLIENTE AND
 A1.CATEGORIA<>A.CATEGORIA));

--CLIENTI CHE HANNO NOLEGGIATO IN TUTTE LE FILIALI DI MILANO
SELECT C.ID_CLIENTE, C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT *
FROM FILIALE F
WHERE F.CITTA='Milano' AND NOT EXISTS (SELECT *
FROM NOLEGGIO N, AUTO A
WHERE N.ID_CLIENTE = C.ID_CLIENTE AND A.TARGA=N.TARGA AND
A.ID_FILIALE=F.ID_FILIALE));

--CLIENTI CHE HANNO NOLEGGIATO ALMENO DUE AUTO DIVERSE
SELECT C.ID_CLIENTE
FROM CLIENTE C
WHERE EXISTS (SELECT *
FROM NOLEGGIO N, NOLEGGIO N1
WHERE N.ID_CLIENTE =C.ID_CLIENTE AND N1.ID_CLIENTE=C.ID_CLIENTE AND
N1.TARGA<>N.TARGA)
