
--CLIENTI CHE HANNO NOLEGGIATO ALMENO DUE AUTO DIVERSE
SELECT C.ID_CLIENTE, C.NOME
FROM CLIENTE C
WHERE EXISTS (SELECT *
FROM NOLEGGIO N, NOLEGGIO N1
WHERE N.ID_CLIENTE =C.ID_CLIENTE AND N1.ID_CLIENTE=C.ID_CLIENTE AND
N1.TARGA<>N.TARGA);

--CLIENTI CHE HANNO EFFETTUATO ESATTAMENTE DUE NOLEGGI
SELECT C.ID_CLIENTE, C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT *
FROM NOLEGGIO N, NOLEGGIO N3
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
N3.ID_CLIENTE=C.ID_CLIENTE AND 
(N3.TARGA<>N.TARGA OR N.DATA_RITIRO<>N3.DATA_RITIRO)
AND NOT EXISTS(SELECT *
FROM NOLEGGIO N1, NOLEGGIO N2
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND 
((N1.TARGA<>N.TARGA OR N1.DATA_RITIRO<>N.DATA_RITIRO) AND 
(N2.TARGA<>N.TARGA OR N2.DATA_RITIRO<>N.DATA_RITIRO) AND
(N1.TARGA<>N2.TARGA OR N1.DATA_RITIRO<>N2.DATA_RITIRO))));

--AUTO NOLEGGIATE DA ALMENO DUE CLIENTI DIVERSI
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE EXISTS(SELECT *
FROM NOLEGGIO N, NOLEGGIO N1
WHERE N.TARGA=A.TARGA AND N1.TARGA=A.TARGA AND 
N.ID_CLIENTE<>N1.ID_CLIENTE);


--CLIENTI CHE HANNO NOLEGGIATO TUTTE LE AUTO SPORTIVE
SELECT C.ID_CLIENTE, C.NOME
FROM CLIENTE C
WHERE NOT EXISTS (SELECT*
FROM AUTO A
WHERE A.CATEGORIA = 'sportiva' AND NOT EXISTS(SELECT *
FROM NOLEGGIO N,AUTO A1
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND N.TARGA = A.TARGA));

--CLIENTI CHE HANNO NOLEGGIATO IN ALMENO TRE CITTÀ DIVERSE
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT *
FROM NOLEGGIO N, NOLEGGIO N1, NOLEGGIO N2,AUTO A, AUTO A1, AUTO A2,
FILIALE F, FILIALE F1, FILIALE F2
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND
N.TARGA = A.TARGA AND N1.TARGA=A1.TARGA AND A2.TARGA=N2.TARGA AND
A.ID_FILIALE = F.ID_FILIALE AND A1.ID_FILIALE=F1.ID_FILIALE AND
A2.ID_FILIALE=F2.ID_FILIALE AND F.CITTA <> F1.CITTA AND
F1.CITTA<>F2.CITTA AND F2.CITTA <> F.CITTA);

--COPPIE DI CLIENTI CHE HANNO NOLEGGIATO LA STESSA AUTO
SELECT C1.NOME, C2.NOME
FROM CLIENTE C1, CLIENTE C2
WHERE C1.ID_CLIENTE<C2.ID_CLIENTE AND EXISTS(SELECT *
FROM NOLEGGIO A, NOLEGGIO B
WHERE A.ID_CLIENTE = C1.ID_CLIENTE AND B.ID_CLIENTE = C2.ID_CLIENTE AND
A.TARGA = B.TARGA);

--CLIENTI CON AUTO ANNO IMMATRICOLAZIONE >2021
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT *
FROM NOLEGGIO N1
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND
NOT EXISTS(SELECT *
FROM NOLEGGIO N, AUTO A
WHERE N.ID_CLIENTE = C.ID_CLIENTE AND N.TARGA=A.TARGA AND
 A.ANNO_IMMATRICOLAZIONE<2021));

--AUTO NOLEGGIATE SOLO UNA VOLTA IN ASSOLUTO
SELECT A.TARGA
FROM AUTO A
WHERE EXISTS
(SELECT *
FROM NOLEGGIO N
WHERE N.TARGA=A.TARGA AND NOT EXISTS(
SELECT *
FROM NOLEGGIO N1
WHERE N1.TARGA=A.TARGA AND (N1.ID_CLIENTE<>N.ID_CLIENTE
OR N1.DATA_RITIRO<>N.DATA_RITIRO)));

--CLIENTI CHE HANNO NOLEGGIATO ALMENO UNA BERLINA, ALMENO UN SUV E 
--ALMENO UNA SPORTIVA
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT N.ID_CLIENTE
FROM NOLEGGIO N,AUTO A 
WHERE N.TARGA=A.TARGA AND A.CATEGORIA='berlina' AND C.ID_CLIENTE=N.ID_CLIENTE
INTERSECT
SELECT N1.ID_CLIENTE
FROM NOLEGGIO N1, AUTO A1
WHERE N1.TARGA=A1.TARGA AND A1.CATEGORIA='SUV' AND C.ID_CLIENTE=N1.ID_CLIENTE
INTERSECT
SELECT N2.ID_CLIENTE
FROM NOLEGGIO N2, AUTO A2
WHERE N2.TARGA=A2.TARGA AND A2.CATEGORIA='sportiva' AND C.ID_CLIENTE=N2.ID_CLIENTE);

--CLIENTI CON ALMENO UN NOLEGGIO CHE NON HANNO MAI NOLEGGIATO DUE VOLTE
--LA STESSA AUTO

SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N 
WHERE N.ID_CLIENTE=C.ID_CLIENTE) AND 
NOT EXISTS(SELECT *
FROM NOLEGGIO N1, NOLEGGIO N2
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND
(N1.TARGA=N2.TARGA AND N1.DATA_RITIRO<>N2.DATA_RITIRO));
