--abbonati che hanno visto almeno una serie della rete r3 e nessuna di r2
SELECT V.USERNAME
FROM VISIONE V
WHERE EXISTS(SELECT *
FROM RETE R,SERIE S
WHERE S.CODICE=V.CODICE AND S.ID_RETE=R.ID_RETE AND R.ID_RETE='R3' AND
NOT EXISTS (SELECT *
FROM RETE R1, SERIE S1
WHERE S1.CODICE=V.CODICE AND S1.ID_RETE=R1.ID_RETE AND R1.ID_RETE='R2'));


--abbonati almeno una serie rete r3 oppure almenp una rete r4
SELECT A.USERNAME
FROM ABBONATO A 
WHERE EXISTS (SELECT V.USERNAME
FROM VISIONE V, SERIE S
WHERE V.USERNAME=A.USERNAME AND S.CODICE=V.CODICE AND S.ID_RETE='R3'
UNION ALL
SELECT V1.USERNAME
FROM VISIONE V1, SERIE S1
WHERE V1.USERNAME=A.USERNAME AND S1.CODICE=V1.CODICE AND S1.ID_RETE='R4');


--ABBONATO CHE NON HANNO VISTO NESSUNA SERIE THRILLER

SELECT A.USERNAME
FROM ABBONATO A
WHERE NOT EXISTS(
SELECT *
FROM VISIONE V, SERIE S
WHERE V.USERNAME=A.USERNAME AND S.CODICE=V.CODICE AND S.GENERE = 'Thriller')
