--abbonati che hanno almeno una visione con voto >=8

SELECT A.USERNAME
FROM ABBONATO A
WHERE EXISTS (SELECT *
FROM VISIONE V
WHERE V.USERNAME=A.USERNAME AND V.VOTO >=8 AND V.VOTO IS NOT NULL);

--abbonati hanno visto tutte le serie Thriller

SELECT A.USERNAME
FROM ABBONATO A
WHERE NOT EXISTS(SELECT *
FROM SERIE S
WHERE S.GENERE = 'Thriller' AND NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.USERNAME = A.USERNAME AND S.CODICE=V.CODICE));

--LE RETI DI CUI ESISTE ALMENO UNA SERIE MAI VISTA DA NESSUN ABBONATO

SELECT R.ID_RETE
FROM RETE R
WHERE EXISTS(SELECT *
FROM SERIE S
WHERE S.ID_RETE = R.ID_RETE AND NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.CODICE=S.CODICE));


--LE SERIE CHE NON SONO STATE VISTE DA NESSUN ABBONATO
SELECT S.CODICE
FROM SERIE S
WHERE NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.CODICE=S.CODICE);

--ABBONATI CHE HANNO VISTO UNA SERIE THRILLER MA NESSUNA DRAMA

SELECT A.USERNAME
FROM ABBONATO A
WHERE EXISTS(SELECT *
FROM VISIONE V, SERIE S
WHERE V.CODICE=S.CODICE AND V.USERNAME=A.USERNAME AND S.GENERE = 'Thriller'
AND NOT EXISTS(SELECT *
FROM VISIONE V1, SERIE S1
WHERE V1.CODICE = S1.CODICE AND V1.USERNAME=A.USERNAME AND S1.GENERE = 'Drama'));

--coppie distinte che hanno visto almeno una in comune
SELECT DISTINCT A.USERNAME, B.USERNAME
FROM VISIONE A, VISIONE B
WHERE A.USERNAME<B.USERNAME AND EXISTS(
SELECT *
FROM SERIE S, SERIE S1
WHERE A.CODICE = S.CODICE AND B.CODICE=S1.CODICE AND 
S.CODICE=S1.CODICE);

--ABBONATI ALMENO UNA SERIE THRILLER
SELECT A.USERNAME
FROM ABBONATO A
WHERE EXISTS(SELECT *
FROM VISIONE V,SERIE S
WHERE V.CODICE=S.CODICE AND A.USERNAME=V.USERNAME AND S.GENERE = 'Thriller');


--reti in cui u01 ha visto tutte le serie

SELECT R.ID_RETE
FROM RETE R
WHERE NOT EXISTS(SELECT *
FROM SERIE S
WHERE R.ID_RETE=S.ID_RETE AND  NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.CODICE=S.CODICE AND V.USERNAME='U01'));

--le serie che hanno nessuna visione ancora in corso
SELECT S.CODICE
FROM SERIE S
WHERE NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.CODICE=S.CODICE AND DATA_FINE IS NULL);
