--gli abbonati che hanno visto tutte le serie della rete 'R1'
SELECT A.USERNAME
FROM ABBONATO A
WHERE NOT EXISTS(SELECT*
FROM RETE R, SERIE S
WHERE S.ID_RETE=R.ID_RETE AND  R.ID_RETE ='R1' AND NOT EXISTS(
SELECT *
FROM VISIONE V
WHERE V.CODICE = S.CODICE AND V.USERNAME=A.USERNAME));

--le coppie di abbonati distinti che hanno visto esattamente lo stesso insieme di
--serie

SELECT A.USERNAME, B.USERNAME
FROM VISIONE A, VISIONE B
WHERE A.USERNAME < B.USERNAME AND NOT EXISTS(
SELECT *
FROM VISIONE C
WHERE C.USERNAME=A.USERNAME AND NOT EXISTS(
SELECT * FROM VISIONE D
WHERE D.USERNAME=B.USERNAME AND D.CODICE=C.CODICE))
AND NOT EXISTS (SELECT *
FROM VISIONE E
WHERE E.USERNAME=B.USERNAME AND NOT EXISTS(
SELECT * 
FROM VISIONE F
WHERE F.USERNAME=A.USERNAME AND F.CODICE=E.CODICE));


--gli abbonati che hanno dato almeno un voto >=8 ma nessun voto <=4 (no NULL)
SELECT A.USERNAME
FROM ABBONATO A
WHERE EXISTS (SELECT *
FROM VISIONE V
WHERE V.USERNAME = A.USERNAME AND V.VOTO >=8)
AND NOT EXISTS (SELECT *
FROM VISIONE V
WHERE V.USERNAME = A.USERNAME AND V.VOTO<=4);


--le serie i cui spettatori provengono tutti dalla stessa città

SELECT DISTINCT V2.CODICE
FROM VISIONE V2
WHERE NOT EXISTS(SELECT *
FROM  VISIONE V, VISIONE V1,ABBONATO A, ABBONATO A1
WHERE V2.CODICE=V.CODICE AND V2.CODICE=V1.CODICE AND
A1.USERNAME=V1.USERNAME AND V.USERNAME=A.USERNAME AND
A1.USERNAME<>A.USERNAME AND A.CITTA<>A1.CITTA);


--le serie per cui non esiste alcuna visione iniziata prima del 01/03/2026
SELECT S.CODICE
FROM SERIE S
WHERE NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.CODICE=S.CODICE AND V.DATA_INIZIO < '01/03/2026');


--gli abbonati che hanno visto solo serie di genere 'Drama' e nessuna serie di 
--altro genere
SELECT A.USERNAME
FROM ABBONATO A
WHERE EXISTS(
SELECT *
FROM VISIONE V, SERIE S
WHERE V.USERNAME=A.USERNAME AND S.CODICE=V.CODICE AND S.GENERE='Drama' AND
NOT EXISTS (SELECT *
FROM VISIONE V1, SERIE S1
WHERE V1.USERNAME=A.USERNAME AND S1.CODICE=V1.CODICE
 AND S1.CODICE <> S.CODICE AND S1.GENERE <> 'Drama'));


--le serie viste da tutti gli abbonati con piano 'Premium'
SELECT S.CODICE
FROM SERIE S
WHERE NOT EXISTS(SELECT *
FROM ABBONATO A
WHERE A.PIANO = 'Premium' AND NOT EXISTS(SELECT *
FROM VISIONE V
WHERE V.CODICE = S.CODICE AND A.USERNAME=V.USERNAME));


--le coppie di abbonati distinti che non hanno alcuna serie in comune
SELECT DISTINCT A.USERNAME, B.USERNAME
FROM VISIONE A, VISIONE B
WHERE A.USERNAME<B.USERNAME AND NOT EXISTS(SELECT *
FROM VISIONE C
WHERE C.USERNAME=A.USERNAME AND NOT EXISTS(SELECT *
FROM VISIONE D
WHERE D.USERNAME=B.USERNAME AND D.CODICE=C.CODICE));
--gli abbonati che hanno almeno una visione ancora in corso (non ancora terminata)

--le reti di cui sono state viste almeno due serie distinte
