--filiale(id_filiale, citta, indirizzo, telefono)
--auto (targa, modello, categoria, anno_immatricolazione, id_filiale)
--cliente(id_cliente, nome, cognome, codice_fiscale, num_patente, email)
--noleggio(targa, id_cliente, data_ritiro, data_riconsegna, km_percorsi,
--valutazione)

--CLIENTI CHE HANNO ALMENO UN NOLEGGIO IN CORSO E ALMENO UNO CONCLUSO
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS (SELECT * FROM NOLEGGIO N WHERE N.DATA_RICONSEGNA IS NULL
AND C.ID_CLIENTE=N.ID_CLIENTE AND
EXISTS(SELECT * FROM NOLEGGIO N1 
WHERE N1.DATA_RICONSEGNA IS NOT NULL AND C.ID_CLIENTE=N1.ID_CLIENTE AND
(N.TARGA<>N1.TARGA OR N.DATA_RITIRO<>N1.DATA_RITIRO)));

--filiali che possiedono almeno un'auto mai noleggiata
SELECT F.ID_FILIALE
FROM FILIALE F
WHERE EXISTS(SELECT * FROM AUTO A
WHERE A.ID_FILIALE=F.ID_FILIALE AND NOT EXISTS(
SELECT * FROM NOLEGGIO N
WHERE N.TARGA=A.TARGA));

--clienti che hanno noleggiato un SUV ma nessuna utilitaria
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS (SELECT * FROM AUTO A, NOLEGGIO N
WHERE A.TARGA=N.TARGA AND N.ID_CLIENTE=C.ID_CLIENTE AND A.CATEGORIA='SUV' 
AND NOT EXISTS (SELECT * FROM AUTO A1, NOLEGGIO N1
WHERE A1.TARGA = N1.TARGA AND N1.ID_CLIENTE=C.ID_CLIENTE AND 
A1.CATEGORIA = 'utilitaria' AND A1.TARGA<>A.TARGA));

--CLIENTI CHE HANNO NOLEGGIATO SIA DALLA FILIALE 1 SIA DALLA 4
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND A.ID_FILIALE=1
INTERSECT
SELECT C.NOME
FROM CLIENTE C, NOLEGGIO N, AUTO A
WHERE C.ID_CLIENTE=N.ID_CLIENTE AND A.TARGA=N.TARGA AND A.ID_FILIALE=4;

--CATEGORIE NOLEGGIATE DA ALMENO TRE CLIENTI DIVERSI
SELECT DISTINCT A.CATEGORIA, A1.CATEGORIA, A2.CATEGORIA
FROM AUTO A, AUTO A1, AUTO A2
WHERE EXISTS(SELECT* FROM NOLEGGIO N1, NOLEGGIO N2, NOLEGGIO N3
WHERE N1.TARGA=A.TARGA AND N2.TARGA=A1.TARGA AND N3.TARGA=A2.TARGA AND
(N1.ID_CLIENTE<>N2.ID_CLIENTE AND N2.ID_CLIENTE<>N3.ID_CLIENTE AND
N3.ID_CLIENTE<>N1.ID_CLIENTE AND A.CATEGORIA=A1.CATEGORIA AND 
A1.CATEGORIA=A2.CATEGORIA AND A2.CATEGORIA=A.CATEGORIA));


--CLIENTI CON ALMENO 4 NOLEGGI
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2, NOLEGGIO N3, NOLEGGIO N4
WHERE C.ID_CLIENTE=N1.iD_CLIENTE AND C.ID_CLIENTE=N2.ID_CLIENTE AND
C.ID_CLIENTE=N3.ID_CLIENTE AND N4.ID_CLIENTE =C.ID_CLIENTE AND
(N1.TARGA<>N2.TARGA OR N1.DATA_RITIRO<>N2.DATA_RITIRO) AND
(N2.TARGA<> N3.TARGA OR N2.DATA_RITIRO<>N3.DATA_RITIRO) AND
(N3.TARGA<>N4.TARGA OR N3.DATA_RITIRO<>N4.DATA_RITIRO) AND
(N4.TARGA<>N1.TARGA OR N4.DATA_RITIRO<> N1.DATA_RITIRO)AND
(N1.TARGA<>N3.TARGA OR N1.DATA_RITIRO<>N3.DATA_RITIRO) AND
(N2.TARGA<>N4.TARGA OR N2.DATA_RITIRO<>N4.DATA_RITIRO));

--AUTO NOLEGGIATE DA ALMENO TRE CLIENTI DIVERSI
SELECT A.TARGA,A.MODELLO
FROM AUTO A
WHERE EXISTS (SELECT * FROM NOLEGGIO N1, NOLEGGIO N2, NOLEGGIO N3
WHERE N1.TARGA=A.TARGA AND N2.TARGA=A.TARGA AND N3.TARGA=A.TARGA AND
N1.ID_CLIENTE<>N2.ID_CLIENTE AND N2.ID_CLIENTE<> N3.ID_CLIENTE AND
N3.ID_CLIENTE<>N1.ID_CLIENTE);

--CLIENTI CHE HANNO NOLEGGIATO ALMENO 4 AUTO DIVERSE
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N1, NOLEGGIO N2, NOLEGGIO N3, NOLEGGIO N4
WHERE C.ID_CLIENTE=N1.ID_CLIENTE AND C.ID_CLIENTE=N2.ID_CLIENTE AND
C.ID_CLIENTE=N3.ID_CLIENTE AND C.ID_CLIENTE=N4.ID_CLIENTE AND
N1.TARGA<>N2.TARGA AND N2.TARGA<>N3.TARGA AND N1.TARGA<>N3.TARGA AND
N1.TARGA<>N4.TARGA AND N2.TARGA<>N4.TARGA AND N3.TARGA<>N4.TARGA);

--CLIENTI CHE HANNO ALMENO UN NOLEGGIO VALUTATO 5 E NON HANNO MAI DATO UN <3
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N 
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND N.VALUTAZIONE=5 AND NOT EXISTS(
SELECT* FROM NOLEGGIO N1 WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND
(N1.TARGA<>N.TARGA OR N1.DATA_RITIRO<>N.DATA_RITIRO) AND 
N1.VALUTAZIONE<3));

--AUTO SOLO VALUTAZIONI =5 E CON ALMENO UN NOLEGGIO VALUTATO
SELECT A.TARGA
FROM AUTO A
WHERE EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.TARGA=A.TARGA AND N.VALUTAZIONE IS NOT NULL AND NOT EXISTS(SELECT * FROM NOLEGGIO N1
WHERE N1.TARGA=A.TARGA AND N1.VALUTAZIONE<>5));

--CLIENTI CHE HANNO UN NOLEGGIO CONCLUSO MA NON VALUTATO
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
N.VALUTAZIONE IS NULL AND N.DATA_RICONSEGNA IS NOT NULL);

--AUTO MAI VALUTATE
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE NOT EXISTS(SELECT * FROM NOLEGGIO N WHERE N.TARGA=A.TARGA AND
N.VALUTAZIONE IS NOT NULL);

--CLIENTI CHE HANNO NOLEGGIATO TUTTE LE AUTO IMMATRICOLATE NEL 2022
SELECT C.NOME
FROM CLIENTE C
WHERE NOT EXISTS(SELECT * FROM AUTO A
WHERE A.ANNO_IMMATRICOLAZIONE = 2022 AND NOT EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.TARGA=A.TARGA AND C.ID_CLIENTE=N.ID_CLIENTE));

--CLIENTI CHE HANNO NOLEGGIATO DA ALMENO TRE FILIALI DIVERSE
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT *
FROM NOLEGGIO N1, AUTO A1, AUTO A2, AUTO A3, NOLEGGIO N2, NOLEGGIO N3
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND
C.ID_CLIENTE=N3.ID_CLIENTE AND N1.DATA_RITIRO<>N2.DATA_RITIRO AND
N2.DATA_RITIRO<>N3.DATA_RITIRO AND N3.DATA_RITIRO<>N1.DATA_RITIRO AND
 A1.TARGA=N1.TARGA AND
A2.TARGA=N2.TARGA AND A3.TARGA=N3.TARGA AND A1.ID_FILIALE<>A2.ID_FILIALE AND
A2.ID_FILIALE<>A3.ID_FILIALE AND A3.ID_FILIALE<>A1.ID_FILIALE);

--AUTO NOLEGGIATE DA TUTTI I CLIENTI CHE HANNO NOLEGGIATO ALMENO UNA SPORTIVA
SELECT A.TARGA, A.MODELLO
FROM AUTO A
WHERE NOT EXISTS(SELECT* FROM CLIENTE C WHERE EXISTS(SELECT *
FROM NOLEGGIO N, AUTO A1 
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND A1.TARGA=N.TARGA AND A1.CATEGORIA='sportiva')
AND NOT EXISTS(SELECT * FROM NOLEGGIO N 
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND N.TARGA=A.TARGA));

--clienti che hannp almeno un noleggio con più chilometri di tutti quelli di paolo
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND NOT EXISTS(SELECT * 
FROM CLIENTE C1, NOLEGGIO N1
WHERE C1.ID_CLIENTE=N1.ID_CLIENTE AND C1.NOME='Paolo' AND C1.COGNOME='Gialli' AND
N.KM_PERCORSI<=N1.KM_PERCORSI));

--clienti con almeno un noleggio ma che non hanno mai noleggiato da filiale roma
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND NOT EXISTS(SELECT *
FROM NOLEGGIO N1, AUTO A, FILIALE F
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND A.TARGA=N1.TARGA AND
A.ID_FILIALE=F.ID_FILIALE AND
F.CITTA='Roma'));

--COPPIA DI AUTO CHE APPARTENGONO ALLA STESSA FILIALE
SELECT A.TARGA, B.TARGA
FROM AUTO A, AUTO B
WHERE A.TARGA<B.TARGA AND NOT EXISTS(SELECT * FROM AUTO C
WHERE C.TARGA=A.TARGA AND NOT EXISTS(SELECT * FROM AUTO D
WHERE D.TARGA=B.TARGA AND C.ID_FILIALE=D.ID_FILIALE)) AND NOT EXISTS(SELECT *
FROM AUTO C WHERE C.TARGA=B.TARGA AND NOT EXISTS(SELECT * FROM AUTO D
WHERE D.TARGA=A.TARGA AND C.ID_FILIALE=D.ID_FILIALE));

--NOLEGGI CON CHILOMETRAGGIO PIÙ BASSO
SELECT N.TARGA, N.ID_CLIENTE
FROM NOLEGGIO N
WHERE N.KM_PERCORSI IS NOT NULL AND NOT EXISTS(SELECT * FROM NOLEGGIO N1
WHERE N1.KM_PERCORSI IS NOT NULL AND N1.KM_PERCORSI<N.KM_PERCORSI);

--CLIENTI CHE HANNO NOLEGGIATO AUTO DI ALMENO DUE CATEGORIE DIVERSI
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT *
FROM NOLEGGIO N1,NOLEGGIO N2, AUTO A1, AUTO A2
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND N2.ID_CLIENTE=C.ID_CLIENTE AND
A1.TARGA=N1.TARGA AND A2.TARGA=N2.TARGA AND 
A1.CATEGORIA<>A2.CATEGORIA);

--CLIENTI CHE HANNO NOLEGGIATO AUTO DI UNA SOLA CATEGORIA
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT * FROM NOLEGGIO N, AUTO A 
WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
A.TARGA=N.TARGA AND NOT EXISTS(SELECT *
FROM NOLEGGIO N1, AUTO A1
WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND A1.TARGA=N1.TARGA AND
A1.CATEGORIA<>A.CATEGORIA));

--CLIENTI DIVERSI DA ANNA BIANCHI CHE HANNO NOLEGGIATO ALMENO UN'AUTO DELLA
--STESSA CATEGORIA DI ANNA BIANCHI
SELECT C.NOME
FROM CLIENTE C
WHERE C.NOME<>'Anna' AND C.COGNOME<>'Bianchi' AND EXISTS(SELECT * 
FROM NOLEGGIO N1, AUTO A1
WHERE C.ID_CLIENTE=N1.ID_CLIENTE AND A1.TARGA=N1.TARGA AND EXISTS(SELECT *
FROM NOLEGGIO N2, AUTO A2, CLIENTE C2
WHERE C2.ID_CLIENTE=N2.ID_CLIENTE AND A2.TARGA=N2.TARGA AND
A2.CATEGORIA=A1.CATEGORIA AND C2.NOME='Anna' AND C2.COGNOME='Bianchi'));

--NOLEGGI SU AUTO SUV CON VALUTAZIONE PARI A 5
SELECT N.ID_CLIENTE, N.TARGA
FROM NOLEGGIO N, AUTO A
WHERE A.TARGA=N.TARGA AND A.CATEGORIA='SUV' AND N.VALUTAZIONE=5;

--CLIENTI CHE HANNO VALUTATO TUTTI I NOLEGGI
SELECT C.NOME
FROM CLIENTE C
WHERE EXISTS(SELECT* FROM NOLEGGIO N WHERE N.ID_CLIENTE=C.ID_CLIENTE AND
NOT EXISTS(SELECT * FROM NOLEGGIO N1 WHERE N1.ID_CLIENTE=C.ID_CLIENTE AND
N1.VALUTAZIONE IS NULL));
